-- Family 8: Privacy, Data Rights, and Regulatory Evidence
-- Bridges auditability and user privacy, mapping Article 30 registries and DSR workflows.

CREATE TABLE public.processing_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    vault_object_id UUID REFERENCES public.vault_objects(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'active',
    name VARCHAR(255) NOT NULL,
    description TEXT,
    purpose TEXT,
    data_categories JSONB DEFAULT '[]'::jsonb,
    data_subject_categories JSONB DEFAULT '[]'::jsonb,
    recipients JSONB DEFAULT '[]'::jsonb,
    cross_border_transfers JSONB DEFAULT '[]'::jsonb,
    retention_schedule TEXT,
    security_measures TEXT,
    joint_controllers JSONB DEFAULT '[]'::jsonb,
    lawful_basis VARCHAR(100),
    is_automated_decision_making BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    owner_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    last_reviewed_at TIMESTAMPTZ,
    next_review_at TIMESTAMPTZ,
    dpia_required BOOLEAN DEFAULT false,
    system_name VARCHAR(255),
    processing_location VARCHAR(100),
    data_sources JSONB DEFAULT '[]'::jsonb,
    special_categories JSONB DEFAULT '[]'::jsonb,
    processor_agreements JSONB DEFAULT '[]'::jsonb,
    version VARCHAR(50),
    is_active BOOLEAN DEFAULT true,
    tags JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    approved_by UUID REFERENCES public.principals(id) ON DELETE SET NULL
);

CREATE TABLE public.data_subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    pseudonymous_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    jurisdiction VARCHAR(100),
    subject_type VARCHAR(100),
    consent_status VARCHAR(50),
    last_active_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT false,
    deleted_at TIMESTAMPTZ,
    anonymized_at TIMESTAMPTZ,
    risk_score NUMERIC(5, 2),
    tags JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    data_categories_present JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE public.data_subject_identifiers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    data_subject_id UUID NOT NULL REFERENCES public.data_subjects(id) ON DELETE CASCADE,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    hash_algorithm VARCHAR(16) DEFAULT 'SHA-256',
    hashed_identifier VARCHAR(255) NOT NULL,
    identifier_type VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    status VARCHAR(50) DEFAULT 'active',
    verified_at TIMESTAMPTZ,
    source_system VARCHAR(100),
    last_seen_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    notes TEXT,
    UNIQUE(organization_id, hashed_identifier, identifier_type)
);

CREATE TABLE public.lawful_basis_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'active',
    basis_type VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    processing_activity_id UUID REFERENCES public.processing_activities(id) ON DELETE CASCADE,
    justification TEXT,
    assessor_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    approval_date TIMESTAMPTZ,
    review_date TIMESTAMPTZ,
    is_valid BOOLEAN DEFAULT true,
    jurisdiction VARCHAR(100),
    applicable_law VARCHAR(255),
    reference_url VARCHAR(1000),
    conditions_met JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    attachment_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL
);

CREATE TABLE public.consent_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    data_subject_id UUID NOT NULL REFERENCES public.data_subjects(id) ON DELETE CASCADE,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    consent_state VARCHAR(50) NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    collection_method VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent TEXT,
    expires_at TIMESTAMPTZ,
    version VARCHAR(50),
    withdrawn_at TIMESTAMPTZ,
    withdrawal_reason TEXT,
    notes TEXT
);

CREATE TABLE public.cross_border_transfer_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'approved',
    source_jurisdiction VARCHAR(100) NOT NULL,
    target_jurisdiction VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    transfer_mechanism VARCHAR(100),
    data_categories JSONB DEFAULT '[]'::jsonb,
    recipient_entity VARCHAR(255),
    assessor_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    approval_date TIMESTAMPTZ,
    review_date TIMESTAMPTZ,
    notes TEXT
);

CREATE TABLE public.dpia_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'draft',
    project_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    processing_activity_id UUID REFERENCES public.processing_activities(id) ON DELETE SET NULL,
    assessor_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    dpo_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    risk_assessment JSONB DEFAULT '{}'::jsonb,
    mitigation_measures TEXT,
    residual_risk_level VARCHAR(50),
    is_approved BOOLEAN,
    approval_date TIMESTAMPTZ,
    next_review_date TIMESTAMPTZ,
    consultation_required BOOLEAN DEFAULT false,
    regulator_consulted BOOLEAN DEFAULT false,
    regulator_response TEXT,
    version VARCHAR(50),
    notes TEXT,
    attachment_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL
);

CREATE TABLE public.data_subject_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    audit_pack_id UUID REFERENCES public.audit_packs(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'received',
    request_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    data_subject_id UUID REFERENCES public.data_subjects(id) ON DELETE SET NULL,
    request_channel VARCHAR(100),
    due_date TIMESTAMPTZ,
    assigned_to UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    identity_verified BOOLEAN DEFAULT false,
    verification_method VARCHAR(100),
    extension_requested BOOLEAN DEFAULT false,
    extension_reason TEXT,
    resolution_type VARCHAR(50),
    resolution_date TIMESTAMPTZ,
    rejection_reason TEXT,
    response_payload_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    processing_duration_ms INTEGER,
    priority VARCHAR(50) DEFAULT 'medium',
    jurisdiction VARCHAR(100),
    notes TEXT,
    tags JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE public.data_subject_request_actions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    request_id UUID NOT NULL REFERENCES public.data_subject_requests(id) ON DELETE CASCADE,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    action_receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    action_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'completed',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    actor_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    duration_ms INTEGER,
    system_affected VARCHAR(255),
    records_affected INTEGER,
    error_message TEXT,
    notes TEXT,
    signature BYTEA,
    signature_algorithm VARCHAR(32),
    hash_algorithm VARCHAR(16),
    action_hash VARCHAR(64),
    payload JSONB
);

CREATE TABLE public.personal_data_references (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    data_subject_id UUID REFERENCES public.data_subjects(id) ON DELETE CASCADE,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    vault_object_id UUID REFERENCES public.vault_objects(id) ON DELETE SET NULL,
    reference_hash VARCHAR(64) NOT NULL,
    hash_algorithm VARCHAR(16) DEFAULT 'SHA-256',
    data_category VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    system_name VARCHAR(100),
    table_name VARCHAR(100),
    column_name VARCHAR(100),
    record_id VARCHAR(255),
    is_encrypted BOOLEAN DEFAULT false,
    encryption_key_id VARCHAR(255),
    is_pseudonymized BOOLEAN DEFAULT false,
    is_anonymized BOOLEAN DEFAULT false,
    anonymized_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT false,
    deleted_at TIMESTAMPTZ,
    retention_date TIMESTAMPTZ,
    purpose VARCHAR(255),
    legal_basis VARCHAR(100),
    source VARCHAR(255),
    confidence_score NUMERIC(5, 4),
    detected_via VARCHAR(100),
    detection_receipt_id UUID,
    is_active BOOLEAN DEFAULT true,
    notes TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    location_uri VARCHAR(1000),
    access_level VARCHAR(50),
    owner_team VARCHAR(100),
    sensitivity_score INTEGER
);

CREATE TABLE public.privacy_redaction_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    gate_evaluation_id UUID REFERENCES public.gate_evaluations(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'completed',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    data_subject_id UUID REFERENCES public.data_subjects(id) ON DELETE SET NULL,
    request_id UUID REFERENCES public.data_subject_requests(id) ON DELETE SET NULL,
    target_reference_id UUID REFERENCES public.personal_data_references(id) ON DELETE SET NULL,
    redaction_method VARCHAR(100),
    actor_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    pre_redaction_hash VARCHAR(64),
    post_redaction_hash VARCHAR(64),
    hash_algorithm VARCHAR(16) DEFAULT 'SHA-256',
    signature BYTEA,
    signature_algorithm VARCHAR(32),
    system_affected VARCHAR(255),
    records_affected INTEGER,
    duration_ms INTEGER,
    error_message TEXT,
    is_verified BOOLEAN DEFAULT false,
    verified_by UUID,
    verified_at TIMESTAMPTZ,
    notes TEXT,
    payload JSONB
);

CREATE TABLE public.privacy_exports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    vault_object_id UUID REFERENCES public.vault_objects(id) ON DELETE SET NULL,
    audit_pack_id UUID REFERENCES public.audit_packs(id) ON DELETE SET NULL,
    export_hash VARCHAR(64) NOT NULL,
    status VARCHAR(50) DEFAULT 'generated',
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    request_id UUID REFERENCES public.data_subject_requests(id) ON DELETE SET NULL,
    data_subject_id UUID REFERENCES public.data_subjects(id) ON DELETE SET NULL,
    hash_algorithm VARCHAR(16) DEFAULT 'SHA-256',
    export_format VARCHAR(50),
    size_bytes BIGINT,
    password_protected BOOLEAN DEFAULT false,
    download_url VARCHAR(1000),
    expires_at TIMESTAMPTZ,
    is_downloaded BOOLEAN DEFAULT false,
    downloaded_at TIMESTAMPTZ,
    downloaded_by UUID,
    generated_by UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    signature BYTEA,
    signature_algorithm VARCHAR(32),
    notes TEXT
);

CREATE TABLE public.retention_policies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    retention_period VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    data_category VARCHAR(100),
    system_target VARCHAR(100),
    jurisdiction VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    owner_id UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    trigger_event VARCHAR(100),
    notes TEXT
);

CREATE TABLE public.legal_holds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    policy_version_id UUID REFERENCES public.policy_versions(id) ON DELETE SET NULL,
    receipt_id UUID REFERENCES public.receipts(id) ON DELETE SET NULL,
    evidence_object_id UUID REFERENCES public.evidence_objects(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'active',
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    target_type VARCHAR(100) NOT NULL,
    target_id UUID NOT NULL,
    reason TEXT,
    requested_by UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    approved_by UUID REFERENCES public.principals(id) ON DELETE SET NULL,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ,
    jurisdiction VARCHAR(100),
    case_reference VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    released_at TIMESTAMPTZ,
    released_by UUID
);

CREATE INDEX idx_processing_activities_org ON public.processing_activities(organization_id);
CREATE INDEX idx_data_subjects_org ON public.data_subjects(organization_id);
CREATE INDEX idx_dsr_org ON public.data_subject_requests(organization_id);
